import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/styles/theme';
import { Box } from '@mui/material';
import Sidebar from '@/components/Sidebar';
import "./globals.css";
import { firebaseConfig } from '@/firebase';
import Login from './login/page';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const isLoggedIn = false;
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {
              isLoggedIn ? (
                <Box
                  sx={{
                    width: '100vw',
                    height: '100vh',
                    bgcolor: 'secondary.main',
                  }}
                  display={'flex'}
                  flexDirection={{ xs: 'column-reverse', sm: 'column-reverse', md: 'row'}}
                >
                  <Sidebar />
                  <Box
                    sx={{
                      p: '1.5rem 3rem',
                      overflow: 'scroll',
                      flexGrow: 1,
                    }}
                  >
                    { children }
                  </Box>
                </Box>
              ) : (
                <Box
                  sx={{
                    p: '1.5rem 3rem',
                    overflow: 'scroll',
                    flexGrow: 1,
                  }}
                >
                  { children }
                </Box>
              )
            }
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
