import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/styles/theme';
import "./globals.css";
import SessionWrapper from '@/components/SessionWrapper';
import { Box } from '@mui/material';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <head>
          <meta name="viewport" content="initial-scale=1, width=device-width" />
        </head>
        <body>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
                {/* <Box
                  sx={{
                    width: '100vw',
                    height: '100vh',
                    bgcolor: 'secondary.main',
                  }}
                  display={'flex'}
                  flexDirection={{ xs: 'column-reverse', sm: 'column-reverse', md: 'row'}}
                >
                  <Sidebar />
                </Box> */}
                  <Box
                    sx={{
                      overflow: 'scroll',
                      flexGrow: 1,
                    }}
                  >
                      { children }
                  </Box>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
